export const TAKE_PICTURE_SUCCESS = 'TAKE_PICTURE_SUCCESS';
export const TAKE_PICTURE_FAILURE = 'TAKE_PICTURE_FAILURE';
export const SWITCH_TYPE = 'SWITCH_TYPE';
export const SWITCH_FLASH = 'SWITCH_FLASH';
