export const FETCH_PHOTO_LIST = 'FETCH_PHOTO_LIST';
export const FETCH_PHOTO_LIST_SUCCESS = 'FETCH_PHOTO_LIST_SUCCESS';
export const FETCH_PHOTO_LIST_FAILURE = 'FETCH_PHOTO_LIST_FAILURE';
export const SET_PAGE = 'SET_PAGE';
