export const FETCH_SEASON_PHOTO_LIST = 'FETCH_SEASON_PHOTO_LIST';
export const FETCH_SEASON_PHOTO_LIST_SUCCESS = 'FETCH_SEASON_PHOTO_LIST_SUCCESS';
export const FETCH_SEASON_PHOTO_LIST_FAILURE = 'FETCH_SEASON_PHOTO_LIST_FAILURE';
export const CHANGE_SEASON = 'CHANGE_SEASON';
export const CHANGE_PAGE = 'CHANGE_PAGE';
