export const images = {
  home: require('../../assets/line/home.png'),
  home_inactive: require('../../assets/line/home_inactive.png'),
  camera: require('../../assets/line/camera.png'),
  camera_inactive: require('../../assets/line/camera_inactive.png'),
  photo: require('../../assets/line/photo.png'),
  photo_inactive: require('../../assets/line/photo_inactive.png'),
  season: require('../../assets/line/season.png'),
  season_inactive: require('../../assets/line/season_inactive.png'),
  spring: require('../../assets/line/spring.png'),
  spring_inactive: require('../../assets/line/spring_inactive.png'),
  spring_white: require('../../assets/line/spring_white.png'),
  summer: require('../../assets/line/summer.png'),
  summer_inactive: require('../../assets/line/summer_inactive.png'),
  summer_white: require('../../assets/line/summer_white.png'),
  autumn: require('../../assets/line/autumn.png'),
  autumn_inactive: require('../../assets/line/autumn_inactive.png'),
  autumn_white: require('../../assets/line/autumn_white.png'),
  winter: require('../../assets/line/winter.png'),
  winter_inactive: require('../../assets/line/winter_inactive.png'),
  winter_white: require('../../assets/line/winter_white.png'),
}
